// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-NZuK8xtRVtL0qoKtoWQAi0jXBZUXpc4',
    appId: '1:868740236158:web:b9ca79968f34e6166ee92f',
    messagingSenderId: '868740236158',
    projectId: 'zc-dodiddone-268df',
    authDomain: 'zc-dodiddone-268df.firebaseapp.com',
    storageBucket: 'zc-dodiddone-268df.appspot.com',
    measurementId: 'G-5H14J2FGGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1IHGMhp3oxVR6poQIaOM01D86bMOhxEQ',
    appId: '1:868740236158:android:df392513b15022f56ee92f',
    messagingSenderId: '868740236158',
    projectId: 'zc-dodiddone-268df',
    storageBucket: 'zc-dodiddone-268df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCHQ_fjWAESDQTIAwnR3nVMX1GzWfj8U',
    appId: '1:868740236158:ios:5af663229c044b6f6ee92f',
    messagingSenderId: '868740236158',
    projectId: 'zc-dodiddone-268df',
    storageBucket: 'zc-dodiddone-268df.appspot.com',
    iosBundleId: 'com.example.zcDodiddone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuCHQ_fjWAESDQTIAwnR3nVMX1GzWfj8U',
    appId: '1:868740236158:ios:5af663229c044b6f6ee92f',
    messagingSenderId: '868740236158',
    projectId: 'zc-dodiddone-268df',
    storageBucket: 'zc-dodiddone-268df.appspot.com',
    iosBundleId: 'com.example.zcDodiddone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-NZuK8xtRVtL0qoKtoWQAi0jXBZUXpc4',
    appId: '1:868740236158:web:c54f5ecda8873ebb6ee92f',
    messagingSenderId: '868740236158',
    projectId: 'zc-dodiddone-268df',
    authDomain: 'zc-dodiddone-268df.firebaseapp.com',
    storageBucket: 'zc-dodiddone-268df.appspot.com',
    measurementId: 'G-GBCVM7SKWG',
  );
}
